// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMP2gdOTOS-33PwehOLziiKN-b_P0timI',
    appId: '1:269775131134:web:9b8b0a374d9dc4da6130af',
    messagingSenderId: '269775131134',
    projectId: 'rentronix-999d6',
    authDomain: 'rentronix-999d6.firebaseapp.com',
    storageBucket: 'rentronix-999d6.firebasestorage.app',
    measurementId: 'G-2ZFRSKSKJ9',
    iosClientId:'269775131134-pl618ubc8m31tchcv1lgta03ok4lkpaa.apps.googleusercontent.com.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk8legz1SGJOBcC0WlvUojMB5R3WCJDE8',
    appId: '1:269775131134:android:b0956c384ff485e76130af',
    messagingSenderId: '269775131134',
    projectId: 'rentronix-999d6',
    storageBucket: 'rentronix-999d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTMgnY1PuqFXqooYmAijFUkWGinRzlLLI',
    appId: '1:269775131134:ios:222cccdc7aee61896130af',
    messagingSenderId: '269775131134',
    projectId: 'rentronix-999d6',
    storageBucket: 'rentronix-999d6.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

}